CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "full_name" varchar,
  "role" varchar NOT NULL DEFAULT 'Customer',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "slug" varchar UNIQUE
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer,
  "name" varchar NOT NULL,
  "description" text,
  "price" decimal(10,2) NOT NULL,
  "discount_price" decimal(10,2),
  "quantity" integer NOT NULL DEFAULT 0,
  "status" integer DEFAULT 1,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "product_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "url" varchar NOT NULL,
  "is_primary" boolean DEFAULT false
);

CREATE TABLE "cart_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "product_id" integer,
  "quantity" integer NOT NULL DEFAULT 1,
  "price_at_add" decimal(10,2)
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "total_amount" decimal(10,2) NOT NULL,
  "status" varchar DEFAULT 'Pending',
  "payment_status" varchar DEFAULT 'Unpaid',
  "shipping_info" json,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "product_id" integer,
  "quantity" integer NOT NULL,
  "unit_price" decimal(10,2) NOT NULL
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "amount" decimal(10,2) NOT NULL,
  "method" varchar,
  "status" varchar,
  "transaction_id" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "content" text NOT NULL,
  "author_id" integer,
  "published_at" timestamp DEFAULT (now()),
  "image_url" varchar
);

COMMENT ON COLUMN "users"."role" IS 'Values: Admin, Customer';

COMMENT ON COLUMN "categories"."slug" IS 'URL friendly: kinh-te-hoc';

COMMENT ON COLUMN "products"."status" IS '1: Active, 0: Inactive';

COMMENT ON COLUMN "orders"."status" IS 'Pending, Processing, Shipped...';

COMMENT ON COLUMN "orders"."shipping_info" IS 'JSON chứa: receiver_name, phone, address';

COMMENT ON COLUMN "payments"."method" IS 'COD, Banking';

COMMENT ON COLUMN "payments"."status" IS 'Pending, Completed, Failed';

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id");
