CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "full_name" varchar,
  "phone_number" varchar,
  "address" text,
  "role" varchar NOT NULL DEFAULT 'Customer',
  "status" varchar NOT NULL DEFAULT 'Active',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text
);

CREATE TABLE "books" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "author" varchar NOT NULL,
  "description" text,
  "price" decimal(10,2) NOT NULL,
  "discount_price" decimal(10,2),
  "stock_quantity" integer NOT NULL DEFAULT 0,
  "image_url" varchar,
  "status" varchar DEFAULT 'Active',
  "category_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "order_date" timestamp DEFAULT (now()),
  "status" varchar NOT NULL DEFAULT 'Pending',
  "receiver_name" varchar NOT NULL,
  "receiver_phone" varchar NOT NULL,
  "receiver_address" text NOT NULL,
  "total_amount" decimal(10,2) NOT NULL,
  "payment_method" varchar NOT NULL,
  "payment_status" varchar DEFAULT 'Unpaid'
);

CREATE TABLE "order_details" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "book_id" integer NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "unit_price" decimal(10,2) NOT NULL
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "content" text NOT NULL,
  "image_url" varchar,
  "user_id" integer,
  "status" varchar DEFAULT 'Published',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "order_details" ("order_id", "book_id");

COMMENT ON COLUMN "users"."role" IS 'Values: Admin, Customer';

COMMENT ON COLUMN "users"."status" IS 'Values: Active, Locked';

COMMENT ON COLUMN "books"."status" IS 'Values: Active, Inactive';

COMMENT ON COLUMN "orders"."status" IS 'Pending, Processing, Shipped, Delivered, Cancelled';

COMMENT ON COLUMN "orders"."payment_method" IS 'COD, Banking';

COMMENT ON COLUMN "orders"."payment_status" IS 'Unpaid, Paid';

COMMENT ON COLUMN "posts"."status" IS 'Values: Draft, Published';

ALTER TABLE "books" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
